apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
